### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by naynu06** [longxiaofei/spider-BaiduIndex#11]
请问有办法录个视频教程吗。。。本人非程序员，但能看得懂一些，但具体操作起来可能比较困难。如果能获得帮助，真是太感谢。。

**Comment by naynu06** [comment]
研读了大半天。。感觉还是很难。能否录制个教程视频手把手教。。或者方便的话可否留下微信，好询问你。。。。

**Comment by nutalk** [comment]
你这样问作者一般是不会答复你的。
你可以网上找一些python教程来学习，然后再来看代码。
或者在身边找个python程序员朋友给你解读。

**Comment by longxiaofei** [comment]
> 研读了大半天。。感觉还是很难。能否录制个教程视频手把手教。。或者方便的话可否留下微信，好询问你。。。。

仅仅是使用的话，您可以百度或者google以下关键词：
1、如何安装python3
2、如何使用pip安装python第三方包
3、如何运行python程序
4、如何使用浏览器获取网页的cookie

**Comment by naynu06** [comment]
感谢你的热心回复。我后面反复看了下代码，，已经可以正常使用这个可视化动画了。。

不过要修改其他内容还不大懂，比如给字体上自定义的颜色，或者加图片等。。



Tao <notifications@github.com> 于2019年8月9日周五 上午9:44写道：

**Comment by naynu06** [comment]
> > 研读了大半天..感觉还是很难。能否录制个教程视频手把手教..或者方便的话可否留下微信，好询问你....
> 
> 只是是使用的话，你可以百度或者google以下关键词：
> 1，如何安装python3 
> 2，如何使用pip安装python第三方包
> 3，如何运行python程序
> 4，如何使用浏览器获取网页的cookie

你好，请问如何获取数据是按月份热度获取而不是按天数热度获取？？？

如果按天数的话，那么我还得在excel表格做求和，请问有办法直接在这个代码里改吗？？

**Comment by naynu06** [comment]
> 你这样问作者一般是不会答复你的。
> 你可以网上找一些蟒教程来学习，然后再来看代码。
> 或者在身边找个蟒程序员朋友给你解读。

你好，请问如何获取数据是按月份热度获取而不是按天数热度获取？？？

如果按天数的话，那么我还得在excel表格做求和，请问有办法直接在这个代码里改吗？？

**Comment by longxiaofei** [comment]
> > > 研读了大半天..感觉还是很难。能否录制个教程视频手把手教..或者方便的话可否留下微信，好询问你....
> > 
> > 
> > 只是是使用的话，你可以百度或者google以下关键词：
> > 1，如何安装python3
> > 2，如何使用pip安装python第三方包
> > 3，如何运行python程序
> > 4，如何使用浏览器获取网页的cookie
> 
> 你好，请问如何获取数据是按月份热度获取而不是按天数热度获取？？？
> 
> 如果按天数的话，那么我还得在excel表格做求和，请问有办法直接在这个代码里改吗？？

1、不可以
2、可以。数据有了，你可以用任何你喜欢的方式去处理数据。

**Comment by naynu06** [comment]
天数整合为月份这个有办法直接在代码改吗？作者的包里有这个代码吗？

LongYu <notifications@github.com> 于2019年8月23日周五 上午7:50写道：
