### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by franklili3** [longxiaofei/spider-BaiduIndex#17]
in demo.py :
from get_index import BaiduIndex

if __name__ == "__main__":
    keywords = ['比特币']
    baidu_index = BaiduIndex(keywords, '2013-04-01', '2014-03-31')
    for index in baidu_index.get_index():
        print(index)

Traceback (most recent call last):
  File "e:/MyProjects/spider-BaiduIndex/new_spider_without_selenium/demo.py", line 6, in <module>
    for index in baidu_index.get_index():
  File "e:\MyProjects\spider-BaiduIndex\new_spider_without_selenium\get_index.py", line 58, in get_index
    keywords=params_data['keywords']
  File "e:\MyProjects\spider-BaiduIndex\new_spider_without_selenium\get_index.py", line 109, in _get_encrypt_datas
    uniqid = datas['data']['uniqid']
TypeError: string indices must be integers

How can I modify the code?

**Comment by longxiaofei** [comment]
#12 
You may need to write a correct cookie in "config.py"

**Comment by franklili3** [comment]
How can I get cookie? I don't understand the method in Readme.MD.

**Comment by franklili3** [comment]
I have opened baidu.com, click Fn + F12, click console tab, write "copy(document.cookie)" and enter, and click Ctrl+C, I have seen the cookie of baidu.com, I have copyed the cookie in COOKIES in config.py. And after I ran demo.py, the error still was  "TypeError: string indices must be integers". What can I do ?

**Comment by longxiaofei** [comment]
click "Fn + F12" -> click "Network" -> refresh page -> click "www.baidu.com" -> copy cookie in "Request Headers"

**Comment by franklili3** [comment]
I have opened baidu.com, click Fn + F12, click "Network" -> refresh page -> click "www.baidu.com" in Name -> copy cookie in "Request Headers" of Headers. I have copyed the cookie to COOKIES in config.py. And after I ran demo.py, 

`from get_index import BaiduIndex
import pandas as pd

if __name__ == "__main__":
    keywords = ['比特币']
    baidu_index = BaiduIndex(keywords, '2013-04-01', '2013-04-30')
    baidu_index_all = pd.DataFrame(columns={'keyword', 'type', 'date', 'index'})
    for index in baidu_index.get_index():
        if index['type'] == 'all':
            index_df = pd.DataFrame(index)
            baidu_index_all.append(index_df)`

> 

> TypeError                                 Traceback (most recent call last)
> 
> g:\zwrk\spider-BaiduIndex\new_spider_without_selenium\demo.py in 
>       7     baidu_index = BaiduIndex(keywords, '2013-04-01', '2013-04-30')
>       8     baidu_index_all = pd.DataFrame(columns={'keyword', 'type', 'date', 'index'})
> ----> 9     for index in baidu_index.get_index():
>       10         if index['type'] == 'all':
>      11             index_df = pd.DataFrame(index)
> 
> g:\zwrk\spider-BaiduIndex\new_spider_without_selenium\get_index.py in get_index(self)
>      56                     start_date=params_data['start_date'],
>      57                     end_date=params_data['end_date'],
> ---> 58                     keywords=params_data['keywords']
>      59                 )
>      60                 key = self._get_key(uniqid)
> 
> g:\zwrk\spider-BaiduIndex\new_spider_without_selenium\get_index.py in _get_encrypt_datas(self, start_date, end_date, keywords)
>     107         html = self._http_get(url)
>     108         datas = json.loads(html)
> --> 109         uniqid = datas['data']['uniqid']
>     110         encrypt_datas = []
>     111         for single_data in datas['data']['userIndexes']:
> 
> TypeError: string indices must be integers


What can I do ?

**Comment by longxiaofei** [comment]
你登录了没有？

**Comment by franklili3** [comment]
刚才没登录，现在我登录了，又复制了一次，[截图](https://kdocs.cn/l/sAFLdTlxD
[金山文档] cookie.docx)，又执行了一次，还是这个错误。

**Comment by longxiaofei** [comment]
不介意的话，将全部new_spider_without_selenium下的代码(config.py包含登录的Cookie)发给我，Email: libra.19951002@gmail.com

**Comment by franklili3** [comment]
发了，请查收，谢谢。

**Comment by longxiaofei** [comment]
我这边使用你的Cookie运行没有任何问题，但是demo.py中pandas相关代码有些bug，请自己查改。

**Comment by LittleSoldiers** [comment]
我也遇到了你这个问题，是没有登录所以才会出现这种问题

**Comment by LittleSoldiers** [comment]
建议使用IE浏览器，我用chrome,刷新好多次都没刷出来

**Comment by yuyangyoung** [comment]
我也遇到了这个问题，可是使用ie刷出的cookies也不对
