### ISSUE TITLE
似乎不能用了，可能是哪里出了问题？

### ISSUE THREAD

**Issue by VeeDou** [longxiaofei/spider-BaiduIndex#2]
![image](https://user-images.githubusercontent.com/27848735/47130180-08a49d00-d2cb-11e8-9cb9-08ec83bdd398.png)

- [x] 下载chromedriver, 并将它放到环境变量中

- [x] 下载tesseract, 并将它放到环境变量中

- [x] 单账号抓取：请你打开百度的首页，登录后，将百度首页的cookie复制后，粘贴到config.py中的COOKIES对象中

- [x] 找到tesseract文件夹, tesseract/3.05.02/share/tessdata/configs中的digits
这些都做了。不知道怎么进行调试

**Comment by longxiaofei** [comment]
应该是分辨率的问题， 我有空改一下。
你也可以在get_index.py的第179尝试修改一下剪切图片的大小。
https://github.com/longxiaofei/spider-BaiduIndex/issues/1

**Comment by VeeDou** [comment]
感谢大佬贡献的代码！
1. 之前不能识别可能的原因是：没有正确配置环境变量。
2. 最后发现是需要自己训练才能识别出来。我参考的是这个，[Tesseract-OCR 图片数字识别的样本训练](https://blog.csdn.net/u012555556/article/details/80666809)

**Comment by longxiaofei** [comment]
> 感谢大佬贡献的代码！
> 
> 1. 之前不能识别可能的原因是：没有正确配置环境变量。
> 2. 最后发现是需要自己训练才能比较准确识别出来。我参考的是这个，[Tesseract-OCR 图片数字识别的样本训练](https://blog.csdn.net/u012555556/article/details/80666809)

是的，即使正确剪切图片后，识别率也只在80%左右，一直考虑重新做一下识别的部分，但一直没有时间，谢谢你提供的参考。

**Comment by VeeDou** [comment]
爬虫好像用不了呢，获取不到   res值

**Comment by longxiaofei** [comment]
已经更新
