### ISSUE TITLE
关于使用COOKIE的问题

### ISSUE THREAD

**Issue by jxyzhx15** [longxiaofei/spider-BaiduIndex#20]
我遇到一个问题是之前粘贴了cookie这后成功运行了，但是今天再次运行的时候就出现了以下错误
Traceback (most recent call last):
  File "demo.py", line 26, in <module>
    for i, keyword_type_date_index in enumerate(baidu_index.get_index()):
  File "C:\Users\jxyzh\Desktop\spider-BaiduIndex-master\baidu_index\baidu_index.py", line 51, in get_index
    encrypt_datas, uniqid = self._get_encrypt_datas(
  File "C:\Users\jxyzh\Desktop\spider-BaiduIndex-master\baidu_index\baidu_index.py", line 84, in _get_encrypt_datas
    uniqid = datas['data']['uniqid']
TypeError: string indices must be integers

我发现之前有人提问过这个问题，不过我这里之前已经成功运行过了，但是今天却报错，换上今天重新粘贴的COOKIE也不行，所以我想问一下有什么办法可以解决吗还是这是百度那里的原因。

非常感谢

**Comment by Dreamkeeper66666** [comment]
> 我遇到一个问题是之前粘贴了cookie这后成功运行了，但是今天再次运行的时候就出现了以下错误
> Traceback (most recent call last):
> File "demo.py", line 26, in
> for i, keyword_type_date_index in enumerate(baidu_index.get_index()):
> File "C:\Users\jxyzh\Desktop\spider-BaiduIndex-master\baidu_index\baidu_index.py", line 51, in get_index
> encrypt_datas, uniqid = self._get_encrypt_datas(
> File "C:\Users\jxyzh\Desktop\spider-BaiduIndex-master\baidu_index\baidu_index.py", line 84, in _get_encrypt_datas
> uniqid = datas['data']['uniqid']
> TypeError: string indices must be integers
> 
> 我发现之前有人提问过这个问题，不过我这里之前已经成功运行过了，但是今天却报错，换上今天重新粘贴的COOKIE也不行，所以我想问一下有什么办法可以解决吗还是这是百度那里的原因。
> 
> 非常感谢

好像百度今天改传值得格式了，加密算法估计也变了。。。我也是今天用不了了

**Comment by longxiaofei** [comment]
> > 我遇到一个问题是之前粘贴了cookie这后成功运行了，但是今天再次运行的时候就出现了以下错误
> > Traceback (most recent call last):
> > File "demo.py", line 26, in
> > for i, keyword_type_date_index in enumerate(baidu_index.get_index()):
> > File "C:\Users\jxyzh\Desktop\spider-BaiduIndex-master\baidu_index\baidu_index.py", line 51, in get_index
> > encrypt_datas, uniqid = self._get_encrypt_datas(
> > File "C:\Users\jxyzh\Desktop\spider-BaiduIndex-master\baidu_index\baidu_index.py", line 84, in _get_encrypt_datas
> > uniqid = datas['data']['uniqid']
> > TypeError: string indices must be integers
> > 我发现之前有人提问过这个问题，不过我这里之前已经成功运行过了，但是今天却报错，换上今天重新粘贴的COOKIE也不行，所以我想问一下有什么办法可以解决吗还是这是百度那里的原因。
> > 非常感谢
> 
> 好像百度今天改传值的格式了，加密算法估计也变了。。。我也是今天用不了了

谢谢提醒，尽快修复

**Comment by longxiaofei** [comment]
已修复，请clone最新的代码

**Comment by Dreamkeeper66666** [comment]
> 已修复，请clone最新的代码

谢谢！刚刚发现原来只是word的格式变了。。。。我还以为改加密算法了。。。。
