### ISSUE TITLE
代码报错string indices must be integers

### ISSUE THREAD

**Issue by yuyangyoung** [longxiaofei/spider-BaiduIndex#22]
test cookies返回正确，但是仍然报错

**Comment by longxiaofei** [comment]
> test cookies返回正确，但是仍然报错

能把除cookie外的代码贴出来吗？

**Comment by yuyangyoung** [comment]
import os
os.chdir(r"E:/百度指数爬虫/spider-BaiduIndex-master2/spider-BaiduIndex-master")


from baidu_index.utils import test_cookies
from baidu_index import config
from baidu_index import BaiduIndex, ExtendedBaiduIndex


cookies = """"""


if __name__ == "__main__":
&nbsp; &nbsp; # 测试cookies是否配置正确
&nbsp; &nbsp; # True为配置成功，False为配置不成功
&nbsp; &nbsp; print(test_cookies(cookies))


&nbsp; &nbsp; Province_code = config.PROVINCE_CODE
&nbsp; &nbsp; City_code = config.CITY_CODE
&nbsp; &nbsp; keywords = ["暴雨"]
&nbsp; &nbsp; city_all_data=[]
&nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; for k,v in City_code.items():&nbsp;&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; baidu_index = BaiduIndex(
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; keywords=keywords,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; start_date='2017-01-01',
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; end_date='2017-12-31',
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; cookies=cookies,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; area=int(v)
&nbsp; &nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; &nbsp; &nbsp; print(k)
&nbsp; &nbsp; &nbsp; &nbsp; for index in baidu_index.get_index():
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; baidu_data = index
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; baidu_data["城市"] = k
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; baidu_data["城市代码"] = v
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; city_all_data.append(baidu_data)
&nbsp; &nbsp; &nbsp; &nbsp; print(k)



麻烦您了
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"龙猪"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月11日(星期一) 上午10:21
收件人:&nbsp;"longxiaofei/spider-BaiduIndex"<spider-BaiduIndex@noreply.github.com&gt;;
抄送:&nbsp;"Young Forever"<690361132@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [longxiaofei/spider-BaiduIndex] 代码报错string indices must be integers (#22)





  
test cookies返回正确，但是仍然报错
  
能把除cookie外的代码贴出来吗？

**Comment by yuyangyoung** [comment]
import os
os.chdir(r"E:/百度指数爬虫/spider-BaiduIndex-master2/spider-BaiduIndex-master")

from baidu_index.utils import test_cookies
from baidu_index import config
from baidu_index import BaiduIndex, ExtendedBaiduIndex

cookies = """"""

if __name__ == "__main__":
    # 测试cookies是否配置正确
    # True为配置成功，False为配置不成功
    print(test_cookies(cookies))

    Province_code = config.PROVINCE_CODE
    City_code = config.CITY_CODE
    keywords = ["暴雨"]
    city_all_data=[]
    
    for k,v in City_code.items():  
        baidu_index = BaiduIndex(
            keywords=keywords,
            start_date='2017-01-01',
            end_date='2017-12-31',
            cookies=cookies,
            area=int(v)
        )
        print(k)
        for index in baidu_index.get_index():
            baidu_data = index
            baidu_data["城市"] = k
            baidu_data["城市代码"] = v
            city_all_data.append(baidu_data)
        print(k)

**Comment by longxiaofei** [comment]
我本机跑这段代码没有任何问题。

不介意的话，可以将您现在使用的cookie发送到我的邮箱。

有可能是`test_cookies`这个方法不太准确，cookie可能并不是有效的cookie，当然也请确保`test_cookies`传入的cookie和`BaiduIndex `传入的cookie是同一个cookie。

之后会尝试添加一个自动登录获取cookie的方法。
