### ISSUE TITLE
关于可能由于被禁而出现string indices must be integers的问题

### ISSUE THREAD

**Issue by Asteria-Sun** [longxiaofei/spider-BaiduIndex#23]
您好！首先非常感谢您的代码！参考您的代码我已经成功爬下了几个关键词的数据（写课程论文用的）！

可能我爬取的数据比较多，在爬取前七个关键词（我一个个爬的）的时候都是正确的，都是再次爬取的时候就又出现了string indices must be integers的报错，这是被网站禁了吗？我更换cookie和ip地址都还是会出现这个报错。

用的程序是在您的最新的程序的基础上加入自己的cookie，其他的未作修改。

**Comment by Asteria-Sun** [comment]
test_cookie的状态是true

**Comment by longxiaofei** [comment]
关键词是什么？

**Comment by Asteria-Sun** [comment]
咦我换了个关键词就可以了，之前搜的是衡水银行就报错了……还是谢谢您！

**Comment by longxiaofei** [comment]
是这样的，衡水银行这个关键词并没有被百度指数收录，目前的代码并没有支持自动过滤不存在的关键词，之后会改进，感谢。

**Comment by Asteria-Sun** [comment]
好的！我知道啦！谢谢大佬！
