### ISSUE TITLE
 TypeError: string indices must be integers

### ISSUE THREAD

**Issue by ffs-sp** [longxiaofei/spider-BaiduIndex#24]
I keep getting this error when I run the whole project. Why?

**Comment by longxiaofei** [comment]
#12

**Comment by ffs-sp** [comment]
@longxiaofei it works now! thanks. 
However, the index results I got seems to be different from what the graph on Baidu shows me... Can I send you the pictures maybe ?

**Comment by longxiaofei** [comment]
> @longxiaofei it works now! thanks.
> However, the index results I got seems to be different from what the graph on Baidu shows me... Can I send you the pictures maybe ?

to my email.
