### ISSUE TITLE
能不能实现多个cookies抓取呀，账号被限制了。。。

### ISSUE THREAD

**Issue by QAQ-Ahuahuahuahua** [longxiaofei/spider-BaiduIndex#27]
爬的指数有些多，单个账号爬好像被限制了，不知道要怎么实现多个账号爬取的功能

**Comment by longxiaofei** [comment]
现在在初始化类的时候，把cookies参数暴露出来了，可以自己尝试批量登录获取cookie，或者手动登录获取cookie。然后自己用多个cookie做一个简单循环就好。
