### ISSUE TITLE
百度指数有两个指标

### ISSUE THREAD

**Issue by FarFly** [longxiaofei/spider-BaiduIndex#3]
一个是 搜索指数， 一个是 资讯指数。 可以爬资讯指数吗，测了下只能爬搜索指数

**Comment by longxiaofei** [comment]
> 一个是 搜索指数， 一个是 资讯指数。 可以爬资讯指数吗，测了下只能爬搜索指数

原理一样，有时间会添加

**Comment by FarFly** [comment]
= = 已经瞎乱改 改出来。主要是那个自定义得点击出来。耗了我半天。如果可以的话，还是希望你来哈哈哈哈

**Comment by longxiaofei** [comment]
> 一个是 搜索指数， 一个是 资讯指数。 可以爬资讯指数吗，测了下只能爬搜索指数



> = = 已经瞎乱改 改出来。主要是那个自定义得点击出来。耗了我半天。如果可以的话，还是希望你来哈哈哈哈

已经添加资讯指数的功能
