### ISSUE TITLE
报错：TypeError string indices must be integers

### ISSUE THREAD

**Issue by cielliyuanpeng** [longxiaofei/spider-BaiduIndex#30]
运行demo时，baidu_index.py 88行 uniqid = datas["data"]["uniqid"] 报错TypeError string indices must be integers

**Comment by longxiaofei** [comment]
cookie正常吗?

**Comment by cielliyuanpeng** [comment]
![cookie](https://user-images.githubusercontent.com/15048475/88365009-4810ef00-cdb7-11ea-808c-93c1a55d7804.png)
cookie复制了这个长字符串，是这样嘛？麻烦您了。

**Comment by longxiaofei** [comment]
```
请你打开百度的首页，登录后，找到www.baidu.com此条GET请求，并复制此条请求的request headers里的cookie，将此cookie粘贴到demo.py中的cookies对象中
```
或者，
你可以直接复制查询指数那个请求中的request headers里的cookie

**Comment by cielliyuanpeng** [comment]
好的，修复了，确实是cookie的问题，感谢。
