### ISSUE TITLE
厉害呀 大神！，就想请问下，1.搜到的结果怎么保存到excel？？

### ISSUE THREAD

**Issue by lan-slot** [longxiaofei/spider-BaiduIndex#31]
厉害呀 ，就想请问下，搜到的结果怎么保存到excel？？ 本人新手小白，pandas ，baidu_index.to_csv('niushi',index = False) 失败呀

**Comment by STU-Zhang-7** [comment]
同问，搜下结果怎么保存到excel！

**Comment by Adam-lxd** [comment]
可以用pandas，用DataFrame装数据，最后调用`to_sql`方法就行。用法可以参考：https://pandas.pydata.org/pandas-docs/version/0.21/generated/pandas.DataFrame.to_csv.html#pandas.DataFrame.to_csv
