### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by ffs-sp** [longxiaofei/spider-BaiduIndex#32]
Hi, I reused this scraper after two months. I used the cookies, "BDUSS" or "H_PS_PSSID", and still returns this error:

  File "/Users/X/Downloads/spider-BaiduIndex-master 3/baidu_index/baidu_index.py", line 84, in _get_encrypt_datas
    uniqid = datas['data']['uniqid']

TypeError: string indices must be integers

This is where I get my cookies from:

<img width="554" alt="Screenshot 2020-07-31 at 16 05 15" src="https://user-images.githubusercontent.com/53754813/89042753-b7528a00-d347-11ea-87e3-172d64cf6075.png">

Thanks..

**Comment by longxiaofei** [comment]
Network -> www.baidu.com -> Headers -> Cookie -> Copy


![WechatIMG76](https://user-images.githubusercontent.com/28337703/89089133-72256b00-d3ce-11ea-958c-81f673c8ac17.jpeg)
