### ISSUE TITLE
key 的请求方式是不是失效了，请求回来的是空值，计算出来的index与网站不一致

### ISSUE THREAD

**Issue by huxin703** [longxiaofei/spider-BaiduIndex#33]

**Comment by longxiaofei** [comment]
我这儿没有任何问题，能麻烦描述清晰一些吗？

**Comment by huxin703** [comment]
用的baidu_index.py选择一个城市，获取关键词的百度指数。
直接调用返回的数值与实际百度指数显示的数值不一致，因此分步使用，查看问题。
首先
url = 'http://index.baidu.com/api/SearchApi/index?' + urlencode(request_args)
html = utils.http_get(url, self.cookies)
datas = json.loads(html)
上面正常返回
 uniqid = datas['data']['uniqid']
key = get_key(uniqid, cookies)
返回key=''
其他计算正常
最后输出的index数值与网页显示不同，用深圳area94，申请广州作为关键词，返回值是260左右，但实际是800多。分步执行和直接执行结果一样。
用charles看了一下，get_key的url没问题，只是返回值不应该为空，我再检查一下问题出在哪里，感谢回复
