### ISSUE TITLE
关键词数据返回

### ISSUE THREAD

**Issue by gjq9593009** [longxiaofei/spider-BaiduIndex#35]
请教前辈，我关键词为上市公司名称，数据返回后，公司名称被分割为单个汉字，这个要如何解决呢？谢谢！
![image](https://user-images.githubusercontent.com/72909809/98456225-f3eb1880-21b5-11eb-9e9e-cea488d80632.png)

**Comment by longxiaofei** [comment]
现在提供组合词查询，但如果只想查询一个关键词的话，请这样写
```
keywords = [['华兴源创'], ['宁德时代']]
```
如果想使用组合词查询，请这样写
```
keywords = [['华兴源创', '股票'], ['宁德时代', '股票']]
```

**Comment by gjq9593009** [comment]
> 现在提供组合词查询，但如果只想查询一个关键词的话，请这样写
> 
> ```
> keywords = [['华兴源创'], ['宁德时代']]
> ```
> 
> 如果想使用组合词查询，请这样写
> 
> ```
> keywords = [['华兴源创', '股票'], ['宁德时代', '股票']]
> ```

谢谢前辈！
