### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by fallcool** [longxiaofei/spider-BaiduIndex#40]
运行DEMO代码报错。cookie正常。之前运行也是正常的。今天突然报错。换了几个cookie仍然报错。我想知道是我的代码的问题还是百度又修改算法了？

**Comment by longxiaofei** [comment]
1. cookie可能不对。之后会考虑做一个百度账号自动登录的功能。
2. cookie可能被BAN了一段时间。

可以尝试用一下我最近更新的代码
