### ISSUE TITLE
作者太牛逼了，顺便问下能抓取百度指数里的“实时”数据么

### ISSUE THREAD

**Issue by lovaxi** [longxiaofei/spider-BaiduIndex#43]
我尝试改了下，发现太笨了搞不定。

调用连接是：http://index.baidu.com/api/LiveApi/getLive

**Comment by lovaxi** [comment]
就是和“七天“在一起的，最近24小时的数据

**Comment by longxiaofei** [comment]
已更新
1. `pip install --upgrade qdata`
2. `examples/test_baidu_index.py`查看示例

**Comment by 380774763** [comment]
太帅了！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "longxiaofei/spider-BaiduIndex"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月7日(星期三) 上午9:05
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [longxiaofei/spider-BaiduIndex] 作者太牛逼了，顺便问下能抓取百度指数里的“实时”数据么 (#43)





 
Closed #43.
