### ISSUE TITLE
请问下request block是不是被封IP了？

### ISSUE THREAD

**Issue by lovaxi** [longxiaofei/spider-BaiduIndex#50]
{"status":10001,"data":"","logid":3107694845,"message":"request block"}

在本地执行又可以在，在服务器上执行了两天就不行了

**Comment by lovaxi** [comment]
我知道了，不是封IP，而是封账号

**Comment by longxiaofei** [comment]
对的，这个项目本身不想提供对网站有过大压力的并发抓取，所以百度登录也只是做二维码登录。

百度指数的话，需要自己控制一下请求频率。

如果需要多账号并发抓取和重试抓取，请自行实现。

感谢支持。
