### ISSUE TITLE
突然遇到未知错误 data.errors.QdataError: 'ERROR-10002: 未知错误'

### ISSUE THREAD

**Issue by zixu12** [longxiaofei/spider-BaiduIndex#51]
之前运行过后没有问题的，突然关闭文件再运行就显示了以下错误：
![image](https://user-images.githubusercontent.com/72136058/116653035-f8e89200-a9b8-11eb-8503-a87afafcec4f.png)
请问有朋友可以看看 如何解决吗

**Comment by lovaxi** [comment]
这就是我上面发帖说的，账号被百度封了。换个账号试试

**Comment by longxiaofei** [comment]
对的，这个项目本身不想提供对网站有过大压力的并发抓取，所以百度登录也只是做二维码登录。

百度指数的话，需要自己控制一下请求频率。

如果需要多账号并发抓取和重试抓取，请自行实现。

感谢支持。

**Comment by zixu12** [comment]
明白啦！谢谢指点～
