### ISSUE TITLE
【BUG】cookies测试成功但是无法获取数据

### ISSUE THREAD

**Issue by Gary2018X** [longxiaofei/spider-BaiduIndex#55]
cookies测试成功，但是数据返回未知错误，建议换个接口测试cookies是否有效

**Comment by longxiaofei** [comment]
👌

**Comment by longxiaofei** [comment]
`test_cookies `这个方法可以废弃掉了，当cookies不可用时，有明显的提示可以看到"cookies不可用"的信息。
