### ISSUE TITLE
验证cookie没问题后，使用百度index依然会说‘cookies失效，请重新获取cookies’

### ISSUE THREAD

**Issue by katrinawuwu** [longxiaofei/spider-BaiduIndex#60]
感谢大佬提供的代码！对于爬虫小白非常有用！
但是依然碰到了cookies失效这个问题，尝试了之前问题里的解决方案，测试cookies结果是True
<img width="548" alt="微信图片_20210917155410" src="https://user-images.githubusercontent.com/90896064/133746126-c4742b53-6c60-4dfb-a936-02c39765db14.png">

**Comment by longxiaofei** [comment]
test_cookies 这个方法不能有效判断该cookies是否可以获取百度指数数据，当cookies不可用时，有明显的提示可以看到"cookies不可用"的信息。

## 如何正确获取cookies

登录之后，浏览百度指数网页，然后再请求baidu.com，复制这个请求的cookie。

或

使用
```
from qdata.baidu_login import get_cookie_by_qr_login

if __name__ == "__main__":
    print(get_cookie_by_qr_login())
```

**Comment by katrinawuwu** [comment]
感谢大佬！我通过第一种方式尝试成功了！
但是比较奇怪的是，我的cookie是以‘BDUSS_BFESS=’开头的，我把它变成‘BDUSS=’就成功了hh

并且使用第二种方法扫描二维码之后我什么都还没做他就说我登录失败。
