### ISSUE TITLE
爬取失败，链接返回不到数据

### ISSUE THREAD

**Issue by zmz125** [longxiaofei/spider-BaiduIndex#65]
在解析的过程中一直报错：
TypeError: string indices must be integers
原来的链接返回以下数据：
{'status': 10018, 'data': '', 'logid': 2418565468, 'message': '您好，百度指数监测到您疑似存在异常访问行为，如您未有类似行为，可能是由于您使用公共网络或访问频次过高，\n        您可以通过邮箱ext_indexfk@baidu.com联系我们'}
获取不到data数据了，是不是百度更换策略了？

**Comment by longxiaofei** [comment]
是改策略了，稍晚时候会更新

**Comment by longxiaofei** [comment]
已更新
