### ISSUE TITLE
接口好像又被

### ISSUE THREAD

**Issue by yi-yi-yi-x** [longxiaofei/spider-BaiduIndex#67]
qdata.errors.QdataError: "ERROR-10002: 未知错误, {'status': 10018, 'data': '', 'logid': 2425414285, 'message': '您好，百度指数监测到您疑似存在异常访问行为，如您未有类似行为，可能是由于您使用公共网络或访问频次过高，\\n        您可以通过邮箱ext_indexfk@baidu.com联系我们'}"

**Comment by longxiaofei** [comment]
控制一下访问频率试一下?

**Comment by yi-yi-yi-x** [comment]
控制了 还找人换了IP地址和账号试了  还是不行

**Comment by yi-yi-yi-x** [comment]
应该确实是接口有问题

**Comment by longxiaofei** [comment]
我目前测试没问题，不介意的话，可以将你使用的cookie发到的我邮箱，要不然我没办法确定是什么问题。

**Comment by yi-yi-yi-x** [comment]
'BIDUPSID=73A8C81194C068939F1527BE0F6F39A2; PSTM=1631081138;
BAIDUID=73A8C81194C0689351B6083A8DB6E944:FG=1;
__yjs_duid=1_aab1a3bf6459824c8d0601ed097d82b41632119619584;
BAIDUID_BFESS=73A8C81194C0689351B6083A8DB6E944:FG=1;
H_WISE_SIDS=110085_127969_132550_184716_185633_188746_189755_194085_194511_194519_197242_197711_197957_198253_199578_201193_201540_202652_203196_203310_203517_203525_204123_204711_204714_204817_204859_204916_205217_205485_205680_206007_206928_206929_207235_207540_207698_207729_207830_207864_207884_208065_208115_208117_208267_208309_208686_208718_208721_208806_209394_209420_209512_209521_209568_209577_209578_209631_209749_209771_209942_210036_210073_210097_210125_210164_210292_210298_210357_210669_210709_210732_210736_210891_210892_210895_210900_210907_211113_211157_211181_211242_211301_211441_211456_211756_211914;
ZD_ENTRY=google; Hm_lvt_d101ea4d2a5c67dab98251f0b5de24dc=1653600726;
__yjs_st=2_OGI2NzgzYmRkNjg4NzczNWQxNGMwYjY0YzYzMmU5YTkxZjEzZmM1MGYwM2MzN2ZlZGEyM2E2MDMxMWNkNTRjZWFkNDQzZjczMWY2NjU1YmVkZDYwMGY4ODk3ZjJhNmQ2ZjZhMmUyYmU0YWU2N2U0OTNlZDNhOGMwZTYwNjQ2ZTg4ODBlZTlkOTI0M2JkZGFmNDVmYTlmNjE0MDg0Njc3ZDNiMTlhMDk4YzI3Y2RmYzllZDFiNmIwY2MyODg3Y2E0XzdfMmU3MDc1MTI=;
BDUSS=zNobkwtdjNEOFJONUJqOGVaSzVpZ2tqbks3MzBvZ0REMC1rT1pWZk9SbTRmN2RpRUFBQUFBJCQAAAAAAAAAAAEAAAAfByrsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALjyj2K48o9iZ;
BDUSS_BFESS=zNobkwtdjNEOFJONUJqOGVaSzVpZ2tqbks3MzBvZ0REMC1rT1pWZk9SbTRmN2RpRUFBQUFBJCQAAAAAAAAAAAEAAAAfByrsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALjyj2K48o9iZ;
Hm_up_d101ea4d2a5c67dab98251f0b5de24dc={"uid_":{"value":"3962177311","scope":1}};
bdindexid=ivno3lj92skj4l2hs4kadstqh6;
ab_sr=1.0.1_YjAxNzA3NWIyNWFlNWU3NWY3ODAwZmYwMTg1MzNjOWE4MGRlODExYzVkNmY4MjkxYjVlNmY5ZDNlMzk4YTE0Mjk0ODgzYmM0YjA4ZmU3YWRjMGVlZWI0ODcwOTM5NWQzMWUzMTg0ODk3MDk5NDUwNjA1Y2I2Yjc0NjQ2YzAyNGZjODlmOTcxNjA3NTQ0NjI2OTA1Yjc1MThkNWU0MGJhOQ==;
Hm_lpvt_d101ea4d2a5c67dab98251f0b5de24dc=1653601035;
RT="z=1&dm=baidu.com&si=ww3o596npw&ss=l3nj6c8i&sl=7&tt=msu&bcn=https://fclog.baidu.com/log/weirwood?type=perf"'

'BIDUPSID=73A8C81194C068939F1527BE0F6F39A2;PSTM=1631081138;BAIDUID=73A8C81194C0689351B6083A8DB6E944:FG=1;BAIDUID_BFESS=73A8C81194C0689351B6083A8DB6E944:FG=1;__yjs_duid=1_aab1a3bf6459824c8d0601ed097d82b41632119619584;H_PS_PSSID=35104_31253_35049_35096_34584_34505_35245_34606_35329_35326_26350_35145_35301;Hm_lvt_d101ea4d2a5c67dab98251f0b5de24dc=1637592469,1638027102,1638324933;BDUSS=k2OERsbENWSVc3ZnozNFhpT2NpcnFCbGxweGV5T0ZLQUhHVERiRWhRTWthTTVoRUFBQUFBJCQAAAAAAAAAAAEAAAAfByrsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACTbpmEk26Zhel;BDUSS_BFESS=k2OERsbENWSVc3ZnozNFhpT2NpcnFCbGxweGV5T0ZLQUhHVERiRWhRTWthTTVoRUFBQUFBJCQAAAAAAAAAAAEAAAAfByrsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACTbpmEk26Zhel;bdindexid=n9ovvart7srumgsjs9ffac67g3;Hm_lpvt_d101ea4d2a5c67dab98251f0b5de24dc=1638325185;ab_sr=1.0.1_ZDVkOTUyZjhkZmU3MjY4YjM5NjQ3NzY3ZDdhN2IwYTRhMWYzMDA0MDg0MTkxMjBlZGVmMmExNzg3YTI4ZjliZWE2MWIwNDM2ZGE5NzRhNjc2M2Q3OGYwNmZkNzQxNDVmZjQ0YjY1NGI0ZDQxN2VkODlhNDFhMTU5NWQwZjA5YjhiOTM5ZDRjZGYwNTM3MDE2MzhiNWQwZDA2Zjg3Y2IwOA==;__yjs_st=2_OGI2NzgzYmRkNjg4NzczNWQxNGMwYjY0YzYzMmU5YTk5OWM4ZmE2MGI2NjBlZmZjZjczYWE0ZTVjMWY1NGQ5YzkxZWE0ZjhmOGE3N2I4ZGM0NmE5YWJjYmFiNTdmMDA4ZmVjNTIyM2E4MjU2OTk2MzgzYzU2NzFmZDk0MzU5MjU1YTAzN2YwNzgzYzIxMWZmNzVhNmFkNzQxNTRjYTQ5M2Q4MGRkNGY1MTdiNjZhYTk4YTdlYjYzODI3NWRmMzk1NTI4NzhmZTMyOTY1NzI3MjlmYjUwYzhkZDBlMWRkZjhmOTZmNmYwZjhhZWMwOTBhZTVhY2IwMzNjM2MzNzkxNF83XzhiMzAxY2Yx;RT="z=1&dm=baidu.com&si=8pas9dbq6r&ss=kwmwczta&sl=8&tt=r8g&bcn=https://fclog.baidu.com/log/weirwood?type=perf&ld=5rle"'

我用这两个cookies试了都不行，还用我的手机流量上网试了也不行。

麻烦了！

感谢！




龙豆丁 ***@***.***> 於 2022年5月28日週六 上午11:46寫道：

**Comment by yi-yi-yi-x** [comment]
我当时在跑一系列关键词，前4个都行，然后就突然不行了

yi xiao ***@***.***> 於 2022年5月28日週六 下午1:18寫道：

**Comment by yi-yi-yi-x** [comment]
方便给个邮箱吗 麻烦了！

**Comment by longxiaofei** [comment]
> 方便给个邮箱吗 麻烦了！

我github上的个人主页有我的邮箱。

另外，我使用你提供的cookies请求了至少20个关键词，目前没发现问题。

可以贴一下你的代码吗?

**Comment by d0nezer0** [comment]
新加的加密参数有一定的有效期， 应该还是请求不合理，加密参数失效之类的。

**Comment by longxiaofei** [comment]
已修正，请更新
`pip install --upgrade qdata`

> 方便给个邮箱吗 麻烦了！
