### ISSUE TITLE
请问如何资讯指数？

### ISSUE THREAD

**Issue by yanyu2015** [longxiaofei/spider-BaiduIndex#68]
目前搜索指数的结果稳定可靠，但是想请教下，如何获得资讯关注中的资讯指数呢？能否点建议，修改哪些代码？

**Comment by longxiaofei** [comment]
`./examples/test_baidu_index.py` `test_get_feed_index` ?

**Comment by yanyu2015** [comment]
感谢大佬！已经搞定了！
