### ISSUE TITLE
请问如何确认api请求中的area编码？

### ISSUE THREAD

**Issue by michael-yangjiayu** [longxiaofei/spider-BaiduIndex#7]
目前area=0的情况下，取到的数据是“全国”数据，请问如何更改area取到各省份/城市的数据呢？
这个api有无相关的接口文档，或者如何确认各种省份/城市选项的编码呢？

感觉找一个词x一段时间，手工对应去做暴力破解会有点麻烦，请问有无其他方法~

**Comment by AheadingSicilia** [comment]
我也遇到了同样的问题，请问xiaofei，如何更改area获取各省份/地区的数据呢？我看到tip里面有写
“- 初始化类时传入area可以查询指定区域的百度指数, 默认为全国”
但还是找不到，如果有空解答的话，非常感谢！

**Comment by longxiaofei** [comment]
> 我也遇到了同样的问题，请问xiaofei，如何更改area获取各省份/地区的数据呢？我看到tip里面有写
> “- 初始化类时传入area可以查询指定区域的百度指数, 默认为全国”
> 但还是找不到，如果有空解答的话，非常感谢！

获取山东地区的指数
```
baidu_index = BaiduIndex(keywords, '2018-01-01', '2019-05-02', area=901)
```

查看城市编码
```
print(BaiduIndex.city_code)
print(BaiduIndex.province_code)
```

**Comment by AheadingSicilia** [comment]
> > 我也遇到了同样的问题，请问xiaofei，如何更改area获取各省份/地区的数据呢？我看到tip里面有写
> > “- 初始化类时传入area可以查询指定区域的百度指数, 默认为全国”
> > 但还是找不到，如果有空解答的话，非常感谢！
> 
> 获取山东地区的指数
> 
> ```
> baidu_index = BaiduIndex(keywords, '2018-01-01', '2019-05-02', area=901)
> ```
> 
> 查看城市编码
> 
> ```
> print(BaiduIndex.city_code)
> print(BaiduIndex.province_code)
> ```

哇，居然回复了！问题太低幼了不好意思！太感谢了！
