### ISSUE TITLE
用老代码，突然指数变为：暂无数据

### ISSUE THREAD

**Issue by zhujianbljh** [longxiaofei/spider-BaiduIndex#75]
想问下：现在用网页打开百度指数，页面显示“暂无数据”，网页RESPNSE为：{"status":10001,"data":"","logid": ****** ,"message":"request block"}。

**Comment by zhujianbljh** [comment]
问题一：最近是什么规则，突然就将账号封了？

**Comment by zhujianbljh** [comment]
问题一：最近是触发了什么规则，突然就将账号封了？      问题二：如何才能解封？是不是必须换账号了？

**Comment by longxiaofei** [comment]
我不太清楚"老代码"是指哪个版本?

**Comment by longxiaofei** [comment]
2022年5月30日，我修正过一次逻辑，2022年5月30日之前的版本都是不可用的。

**Comment by zhujianbljh** [comment]
就是5月30日之前的，这两天才看到又修正了，但在前几天用老的（自已参考着写的代码）运行过几次了，结果就是百度指数看不到数据，不仅后台爬不到，正常浏览网页也不显示数据。如一楼所示。

**Comment by longxiaofei** [comment]
所以用一下新的?

**Comment by zhujianbljh** [comment]
好的。我纠结的是这个账号彻底不能用了，如何解。。。

**Comment by longxiaofei** [comment]
1. 过一段时间再试试
2. 清掉百度相关的cookies重新登录(可以新开一个无痕浏览器，登录试一下)

**Comment by chenzhg-maker** [comment]
应该爬太多数据了，我刚刚也遇到同样的问题

**Comment by chenzhg-maker** [comment]
请问大概封了多久？

**Comment by zhujianbljh** [comment]
最后还是换了账号，就好了。短时间看不到解封的可能

**Comment by chenzhg-maker** [comment]
> 最后还是换了账号，就好了。短时间看不到解封的可能

多谢回复。我已解决问题，大概每次封号时间是半天到一天不定。
