### ISSUE TITLE
部分地区数据无法抓取？

### ISSUE THREAD

**Issue by July-cy** [longxiaofei/spider-BaiduIndex#8]
在对某些地区的数据进行爬取时会报错：list index out of range，想请问要怎么办？
比如针对源代码中给出的几个关键字，地区代码设为32（湖北襄阳）时会报错。
希望能得到答复，谢谢~

**Comment by longxiaofei** [comment]
晚上会更新

**Comment by July-cy** [comment]
太感谢啦~~
