### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by yixin-mei** [longxiaofei/spider-BaiduIndex#80]
请问出现以下报错应该怎么解决呢，谢谢!

qdata.errors.QdataError: "ERROR-10002: 未知错误, {'status': 10002, 'data': '', 'logid': 2546662798, 'message': 'bad request'}"

**Comment by longxiaofei** [comment]
把qdata的version和你的传参(keywords_list, start_date, end_date)贴一下

**Comment by DawudMa** [comment]
> 请问出现以下报错应该怎么解决呢，谢谢!
> 
> qdata.errors.QdataError: "ERROR-10002: 未知错误, {'status': 10002, 'data': '', 'logid': 2546662798, 'message': 'bad request'}"

我也遇到了这个问题。
经过排查发现是关键词未被收录的原因。

**Comment by longxiaofei** [comment]
如果是这样，之后会考虑添加一个检查关键词是否被收录的方法。

**Comment by DawudMa** [comment]
> 如果是这样，之后会考虑添加一个检查关键词是否被收录的方法。

这个功能对于关键词库的有效性检验会非常有帮助。

**Comment by longxiaofei** [comment]
检查关键词方法已加，之后可以参考以下代码进行百度指数的获取 `./examples/baidu_index_best_practice.py`
