### ISSUE TITLE
关于 'ERROR-10003: 网络错误' 建议

### ISSUE THREAD

**Issue by DawudMa** [longxiaofei/spider-BaiduIndex#83]
该错误会在大规模任务中随机触发，具体的原因尚不清楚。
但可以肯定的是，并非爬虫频繁获取数据导致的。
当前任务的时间间隔在20s，大部分情况下运行稳定，出现该问题重启任务会正常获取到数据。
目前采取的策略是在请求部分增加一个3次重试的机制来解决。

**Comment by longxiaofei** [comment]
可以参考以下代码进行百度指数的获取 `./examples/baidu_index_best_practice.py`
