### ISSUE TITLE
账号限制查询

### ISSUE THREAD

**Issue by sjq1271227116** [longxiaofei/spider-BaiduIndex#85]
有遇到一个账号爬多了，被限制访问吗，即使自己电脑浏览器打开百度指数也没数据了
还有问一下遇到这个问题的同学，被限制后多久恢复正常

**Comment by ssyfj** [comment]
我也遇到了，无语了

**Comment by sjq1271227116** [comment]
> 我也遇到了，无语了

已经解封了，大约10天账号就恢复正常了
